export interface Project {
  id: string;
  title: string;
  description: string;
  problem: string;
  solution: string;
  tech: string[];
  github: string;
  live: string;
  featured: boolean;
}

export const projects: Project[] = [
  {
    id: "blog-platform",
    title: "Fully Dynamic Blog Website",
    description: "A sophisticated, modern blog platform featuring personalized email subscriptions, intelligent user interest tracking, and a content paywall system.",
    problem: "Content creators struggle to retain audiences and monetize without forcing users onto rigid third-party platforms.",
    solution: "Architected a full-stack platform with intelligent user tracking, targeted email subscriptions via Brevo, and a built-in paywall managed by a multilingual admin dashboard.",
    tech: ["React", "Node.js", "Express", "MongoDB", "Tailwind", "Brevo API"],
    github: "https://github.com/Solanki028/Astroxhub-Blogs",
    live: "https://www.innvibs.com",
    featured: true,
  },
  {
    id: "task-generator-ai",
    title: "Task Generator AI",
    description: "An intelligent project planning tool that uses AI to generate comprehensive specifications, user stories, and engineering tasks.",
    problem: "Project managers spend hours manually breaking down high-level ideas into actionable, prioritized engineering tasks.",
    solution: "Integrated LLMs to automatically generate comprehensive specs, user stories, and Jira-ready tasks from simple descriptions, complete with markdown export.",
    tech: ["React", "Node.js", "MongoDB", "Tailwind", "Gemini / OpenAI"],
    github: "https://github.com/Solanki028/Task-Generator-AI",
    live: "https://taskaiflow.netlify.app/",
    featured: true,
  },
  {
    id: "smart-bookmark-app",
    title: "Smart Bookmark App",
    description: "A production-ready bookmark manager featuring instant Google OAuth, real-time data sync, and optimistic UI updates.",
    problem: "Developers lose track of valuable resources without a fast, cross-device synchronized system that acts instantly.",
    solution: "Built a Next.js 14 application with Supabase Row Level Security (RLS) and optimistic UI mutations for instant, secure bookmarking across devices.",
    tech: ["Next.js 14", "TypeScript", "Supabase Auth", "PostgreSQL", "Tailwind CSS"],
    github: "https://github.com/Solanki028/Smart-bookmark-app",
    live: "https://smart-bookmark-app-eosin.vercel.app/",
    featured: true,
  },
  {
    id: "nwb-fintech",
    title: "NWB Fintech Infrastructure",
    description: "A comprehensive, enterprise-grade fintech platform demonstrating next-generation payment solutions and real-time analytics.",
    problem: "Legacy banking interfaces fail to provide modern features like zero-latency UI dashboards and clear global card processing views.",
    solution: "Developed a Next-Gen UI using React, Shadcn, and Framer Motion, demonstrating advanced UPI collections and banking-as-a-service modules.",
    tech: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Shadcn UI", "Recharts"],
    github: "https://github.com/Solanki028/crimson-flow",
    live: "https://vaultpayy.netlify.app/",
    featured: true,
  },
  {
    id: "velora-spa",
    title: "Velora Spa & Massage",
    description: "A modern, full-stack wellness website with comprehensive CMS and booking functionality.",
    problem: "Local wellness businesses lack professional online presence and seamless booking systems.",
    solution: "Delivered a custom headless CMS backend via Express/MongoDB and a high-performance customer-facing Next.js frontend for easy bookings.",
    tech: ["Next.js", "Express.js", "MongoDB", "Tailwind CSS", "Framer Motion"],
    github: "https://github.com/Solanki028/serene-zen-booking",
    live: "https://veloraaspa.netlify.app/",
    featured: true,
  },
  {
    id: "ilp-lms",
    title: "ILP: Internship Platform",
    description: "A comprehensive Learning Management System designed to bridge the gap between students and mentors.",
    problem: "Managing courses, mentors, and students simultaneously required multiple disparate platforms.",
    solution: "Engineered a centralized platform featuring role-based access control, interactive course management, and automated PDF certification generation.",
    tech: ["React.js", "Node.js", "Express.js", "MongoDB", "JWT Auth", "PDFKit"],
    github: "https://github.com/Solanki028/TDD-intersnhip-learning-platform",
    live: "https://mytutorx.netlify.app/",
    featured: true,
  },
  {
    id: "taskflow-ai",
    title: "TaskFlow: AI Powered Trello",
    description: "A modern, full-stack task management platform with intelligent AI recommendations.",
    problem: "Standard Kanban boards lack context-aware recommendations for task grouping and deadlines.",
    solution: "Implemented an AI recommendation engine that analyzes card content to suggest due dates, list movements, and related tasks alongside a robust drag-and-drop UI.",
    tech: ["React", "TypeScript", "Node.js", "MongoDB", "@dnd-kit"],
    github: "https://github.com/Solanki028/TaskFlow",
    live: "https://trellox.netlify.app/",
    featured: false,
  },
  {
    id: "jk-designs",
    title: "JK Designs Portfolio",
    description: "A premium, high-performance portfolio for a creative design studio with a custom CMS.",
    problem: "Creative studios need blazing-fast websites with full control over their visual assets without relying on slow builders.",
    solution: "Delivered a custom Next.js frontend connected to a dedicated Node.js admin dashboard to manage images and site content in real-time.",
    tech: ["Next.js", "React", "Node.js", "Express", "MongoDB"],
    github: "https://github.com/Solanki028/client-porfolio",
    live: "https://zencraftx.netlify.app/",
    featured: false,
  },
  {
    id: "flix-chill",
    title: "Flix-Chill Video Streaming Platform",
    description: "Netflix-inspired video streaming platform built with MERN stack featuring user authentication and video playback.",
    problem: "Building a scalable media-heavy application requires robust content delivery and state management.",
    solution: "Engineered a high-performance MERN stack application utilizing Redux for global state and Material-UI for responsive, cinematic viewing experiences.",
    tech: ["React.js", "Redux", "Express.js", "MongoDB", "Tailwind CSS"],
    github: "https://github.com/Solanki028/Netflix_",
    live: "https://flixchillv1.netlify.app/",
    featured: false,
  },
  {
    id: "insider-jobs",
    title: "Insider Jobs Portal",
    description: "Professional job portal connecting job seekers with recruiters featuring job tracking and real-time updates.",
    problem: "Candidate application tracking across multiple postings is notoriously scattered and difficult for recruiters.",
    solution: "Developed secure Clerk-authenticated dashboards linking job seekers with recruiters using Redux and a central MongoDB system.",
    tech: ["React", "Material-UI", "Redux", "Node.js", "Clerk Auth"],
    github: "https://github.com/Solanki028/InsiderJobs",
    live: "#",
    featured: false,
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker App",
    description: "Comprehensive expense tracking application with budget management and spending visualization.",
    problem: "Users often lack clear visual insights into their spending habits.",
    solution: "Integrated Chart.js inside a MERN stack application to deliver instant visual financial insights and robust budget tracking.",
    tech: ["React.js", "Express.js", "MongoDB", "Tailwind CSS", "Chart.js"],
    github: "https://github.com/Solanki028/Expense-Tracker",
    live: "#",
    featured: false,
  },
  {
    id: "weather-detection",
    title: "Weather Detection Platform",
    description: "Real-time weather application fetching data from external APIs with beautiful visual representations.",
    problem: "Reliable real-time environmental data must be parsed and displayed intuitively across devices.",
    solution: "Consumed third-party Weather APIs via standard React to deliver instantaneous global forecasts wrapped in elegant Material-UI components.",
    tech: ["JavaScript", "React", "Material-UI", "Weather API"],
    github: "https://github.com/Solanki028/weather-app-react",
    live: "#",
    featured: false,
  },
  {
    id: "modern-todo",
    title: "Modern Todo Application",
    description: "Feature-rich task management application with category organization and persistent storage.",
    problem: "Basic todo apps fail to scale effectively to handle categorized persistence.",
    solution: "Built a fully persistent task execution tool utilizing Node.js and MongoDB attached to a snappy React frontend.",
    tech: ["React.js", "Express.js", "MongoDB", "Node.js"],
    github: "https://github.com/Solanki028/Todo-App-react",
    live: "#",
    featured: false,
  }
];
